### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [miraflow/DistilDIRE#6]
Hi,
Thanks for releasing Distil-DIRE! Would you mind adding a license to this repo?
Thanks!

**Comment by aerinkim** [comment]
Hi there, 
This work is licensed under the Creative Commons Attribution-NonCommercial 4.0 license.
You are free to read, share, and modify this code as long as you keep the original author attribution and non-commercial license.
Please see [this site](https://creativecommons.org/licenses/by-nc/4.0/) for detailed legal terms.
