### ISSUE TITLE
Improve discoverability of your work on HF

### ISSUE THREAD

**Issue by NielsRogge** [miraflow/DistilDIRE#7]
Hi,

Niels here from the open-source team at Hugging Face. I discovered your work through the paper page: https://huggingface.co/papers/2406.00856 (feel free to claim the paper so that it appears at your HF account!).

However there are a couple of things which could improve the discoverability of your work, which I've listed below.

## Upload models and link them to the paper

It would be great to upload the checkpoints to the hub, along with model cards and tags so that people find them when filtering hf.co/models.

See here for a guide: https://huggingface.co/docs/hub/models-uploading

Regarding a model card along with metadata tags, here's a guide: https://huggingface.co/docs/huggingface_hub/en/guides/model-cards

It would be great to link the models to the paper, see here on how to do that: https://huggingface.co/docs/hub/en/model-cards#linking-a-paper

Let me know if you need any help regarding this!

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by yevvonlim** [comment]
Thank you for your kindness :) We have pushed our model to the HF page.

**Comment by NielsRogge** [comment]
Thank you!

However, it seems like you've pushed the entire Github repository to the hub, ideally only the checkpoints are pushed, each to separate model repositories :)

Would also be great to link them in the README of this Github repository!
